# Les préamplificateurs

Le rôle d’un préampli est de réaliser une amplification en tension du signal ainsi que de diminuer son impédance. Cette opération est indispensable pour permettre à notre signal de traverser le reste de la chaîne du traitement audio.

Il n’est pas rare que les préamplificateurs soient souvent choisis pour leur « couleur » sur le signal. Nous commencerons par aborder ces outils d’un point de vue pratique pour enfin déboucher sur cette question.

## Critères de choix d’un préamplificateur

Le critère de première importance dans le choix d’un préamplificateur est son gain maximal. Plus l’amplification disponible est grande, plus le préampli sera capable de répondre à des situations exigeantes, telles que l’enregistrement d’un évènement sonore à faible niveau, ou l’emploi d’un microphone à faible sensibilité.

Le second critère important dans le choix d’un préampli est sa réponse en fréquence. Théoriquement, celle-ci doit être la plus neutre possible. Une certaine coloration peut être acceptée (voire souhaitée), mais celle-ci doit rester raisonnable pour répondre à des critères d’utilisations professionnelles.

La réponse en transitoire est un autre élément important. Certains préamplis auront tendance à adoucir la sensation d’attaque des sources. Cet effet n’est pas souhaitable.

Enfin le rapport signal sur bruit doit être le plus grand possible. Nous cherchons toujours à rajouter le moins de bruit possible sur le chemin de notre signal.

## Les technologies de préampli

Nous avons vu dans le chapitre trois qu’il existe trois familles de composants électroniques permettant d’amplifier le signal : les tubes, les transistors et les circuits intégrés. On retrouve donc des topologies de circuit de préamplificateurs utilisant chacun de ces composants.

Chacune de ces topologies offre de très légère variation de son lorsque les préamplis sont poussés dans leur retranchement (seuil de saturation). Comme pour les microphones, il est délicat de parler de son « à tube » ou « à transistor ». De plus, l’influence sur le son d’un préamplificateur apparaît en pratique comme très marginale par rapport au positionnement du microphone.

## Les réglages d’un préampli

Un préampli propose souvent les réglages suivants :

+ Un potentiomètre de gain (qui est souvent remplacé par un sélecteur cranté, plus précis, pour les modèles haut de gamme).
+ Un bouton activant l’alimentation fantôme. En effet, c’est bien le préampli qui génère cette tension d’alimentation pour les microphones statiques.
+ Un bouton d’inversion de phase.
+ Un coupe-bas.