# Enceintes et salle d'écoute

De tous les équipements audio nécessaires pour réaliser une prise de son, les enceintes (et les casques) sont certainement les plus importants. En effet, c’est sous leurs influences que nous pourrons écouter et contrôler notre travail. Il est donc crucial d’utiliser des écoutes regroupant un certain nombre de critères minimaux et de les connaître sur le bout des doigts.

## Choisir une paire d’écoutes

Choisir une paire d’enceintes peut paraître être un exercice difficile. Il existe énormément de modèles, parcourant des gammes de prix allant de quelques dizaines d’euros à plusieurs dizaines de milliers.

Qui plus est, l’enceinte audio est sans doute l’appareil audio que les Hommes savent le moins bien fabriquer. L’enceinte de monitoring parfait, à savoir linéaire en tout point, n’existe pas.

Premièrement, nous ne savons pas fabriquer des haut-parleurs capables de reproduire uniformément toutes les fréquences. Ces derniers sont souvent spécialisés dans une certaine plage de fréquence. La plupart des enceintes de monitoring utilisent 3 voies : deux actives (utilisant des haut-parleurs) pour l’aigu et le médium, et une passive (évent avant ou arrière) pour le grave.

Deuxièmement, un haut-parleur peut être approché par un modèle « masse-ressort ». Cela signifie qu’il y a une certaine inertie à sa mise en action et une certaine inertie à sa mise en arrêt. L’enceinte idéale devrait posséder une inertie nulle dans les deux cas, ce qui n’est malheureusement pas le cas en pratique. Cette inertie est potentiellement responsable d’un adoucissement des transitoires et d’une sensation de flou. 

Il y a cependant plusieurs critères assez objectifs pour évaluer la qualité d’une enceinte :

1. La réponse en fréquence : l’enceinte flatte-t-elle particulièrement une zone du spectre ? En délaisse-t-elle une autre ?
2. La réponse en transitoires : les attaques sont-elles respectées ? Retrouve-t-on l’énergie initiale du signal ?
3. La linéarité en fonction du volume : a-t-on une sensation de compression du signal lorsque l’on augmente le niveau envoyé dans l’enceinte ?
4. Le centre fantôme : le centre du système stéréophonique paraît-il stable ? Paraît-il précis ?
5. La couleur sonore de l’enceinte : a-t-on plaisir à écouter du son et de la musique sur ce système ?

## Placer correctement son écoute

Afin de satisfaire les critères de la stéréophonie, il convient de respecter les règles suivantes :

+ Les deux enceintes doivent être de même marque, de même modèle et appairée. Si une des membranes a dû être changée sur l’une d’elle, l’autre aurait dû recevoir la même opération.
+ Les deux enceintes
+  doivent être séparées d’un angle de 60°
+ L’auditeur doit être placé à équidistance des deux haut-parleurs, et regarder vers le milieu du segment formé par les deux enceintes.

Une fois ces critères respectés, voici quelques conseils sur le placement des enceintes dans une pièce :

+ On préférera des pièces de grandes tailles, afin de repousser au maximum le temps d’arrivée des premières réflexions.
+ Le système stéréophonique devrait être positionné dans un souci de symétrie : l’enceinte de gauche ne devrait pas être plus proche d’un mur que l’enceinte de droite, par exemple.
+ Dans le cas de petit espace, on préféra coller les enceintes contre un mur. Cela permettra de supprimer l’influence d’une des premières réflexions au prix de l’augmentation du niveau de grave.
+ Il est vivement recommandé de procédé au traitement, même minimal, acoustique de la pièce de travail, à commencer par les zones de réflexions premières et par les angles (ou le grave va s’accumuler).
+ Si le traitement acoustique n’est pas envisageable, il convient de privilégier une écoute à faible niveau et une proximité maximale avec les enceintes.

## L'écoute au casque

Le casque est un outil permettant d'écouter un signal tout en s'extrayant de son environnement (acoustique et/ou bruit). Cependant, de par son mode de fonctionnement, à savoir deux haut-parleurs placés dans une enceinte en contact direct avec les oreilles, il génère un certain nombre de déformations.

Premièrement, la stéréophonie écoutée au casque est hypertrophiée. En effet, dans ces conditions d'écoutes, l'oreille gauche n'entend que le haut-parleur gauche et l'oreille droite n'entend que le haut-parleur droit.

Deuxièmement, il est très difficile de trouver des casques avec une réponse en transitoire satisfaisante. Il convient donc d'être excessivement prudent lorsque l'on mix du contenu percussif sur un casque.

Troisièmement, les casques sont encore moins linéaires en fréquence que les haut-parleurs, il convient là aussi d'être très prudent lors de la réalisation d'un mixage.

Ces défauts peuvent être compensés par l'habitude et la connaissance du système d'écoute, mais la transportabilité d'un mixage (à savoir, sa compatibilité avec d'autres systèmes d'écoute) réalisé au casque est souvent discutable.

## Casque fermé ou casque ouvert ?

Le casque fermé, comme son nom l'indique, propose une fabrication enfermant le haut-parleur dans une enceinte close. Cette méthode de fabrication offre l'avantage d'isoler celui qui écoute de l'environnement, mais aussi d'isoler l'environnement de ce qui est diffusé dans le casque. Par contre, ces casques ont souvent une réponse en fréquence très accidentée, et ne sont pas recommandés pour le mixage. Il est par contre vivement recommandé pour les musiciens en session de prise de son.

Le casque ouvert, à l'inverse de son homologue fermé, n'offre aucune isolation acoustique, au prix d'une meilleure réponse en fréquence du casque. Ces casques sont tout indiqués pour le mixage, mais beaucoup moins pour des situations de prise de son.
