---
title: "Formation prise de son et mixage"
subtitle: "Evaluation"
author: "Jean-Loup Pecquais"
date: "2021/11/28"
output:
  pdf_document: default
---

# Prise de son

1. Listez, selon vous, les différents maillons de la chaine de production audio, de l'enregistrement à la diffusion.

1. Parmi ces propositions, la ou lesquelles, ne sont pas des directivités de microphones ?
    + Cardioïde
    + Ruban
    + Omnidirectionnelle
    + Figure en huit

1. Parmi ces propositions, lesquelles sont-elles vraies ?
    + Les microphones dynamiques offrent une bonne restitution des hautes fréquences
    + Les microphones à ruban demandent une alimentation afin de fonctionner
    + Les microphones statiques sont les types de microphones les plus sensibles

1. L'impédance d'un câble à une grande importance sur le résultat sonore d'un enregistrement :
    + vrai
    + faux

1. Un préamplificateur permet :
    + De réduire le souffle d'une prise
    + De mettre en forme le signal 
    + De réaliser une amplification en tension

1. La conversion analogique/numérique :
    + permet de passer d'un signal continu à un signal échantillonné
    + ne permet pas, à 48 kHz, de reproduire fidèlement le spectre audio
    + introduit une dégradation évidente du signal

1. Concernant la dynamique de quantification :
    + Un bit équivaut à 6 dB de dynamique
    + La dynamique d'un CD (16 bit) n'est pas suffisante pour reproduire de la musique très dynamique.
    + Le réglage de quantification définit le plancher de bruit du signal.

1. Cochez les informations vraies
    + Le bruit est l'ennemie de l'analogique
    + La latence est l'ennemie du numérique

1. La stéréophonie :
    + est un dispositif de diffusion prévu pour le casque
    + est un dispositif de prise de son
    + est un dispositif de diffusion sur deux enceintes écartées de 60° formant un triangle isocèle avec l'auditeur.

1. Cochez les informations vraies
    + Un couple XY est un couple de prise de son non coïncident
    + Il n'existe que les couples AB, XY et ORTF.
    + Les abaques de Michael Williams permettent de définir, pour un angle de prise de son donné, des couples de prises de son en fonction de la directivité et de l'écartement des microphones.

# Mixage

1. Afin de commencer un mixage audio sur des bases saines, il convient :
    + De nettoyer le grave de toutes les pistes avec un coupe bas
    + De chercher à améliorer les interactions de phase entre les signaux
    + De préparer le routage de sa session

1. La phase :
    + est audible sur un seul signal
    + affecte la façon dont se somment des signaux

1. Indiquez trois facteurs qui introduisent de la différence de phase entre deux signaux.

1. L'étape la plus importante d'un mixage est :
    + L'égalisation
    + La gestion de la dynamique
    + La balance

1. L'égalisation :
    + permet de rattraper une prise de son ratée.
    + permet de placer les sources dans un mixage
    + doit absolument être utilisée en soustractif

1. La compression :
    + Permet d'automatiser la variation de niveau sonore d'une source.
    + Remonte les bas niveaux
    + Peut permettre d'augmenter l'attaque d'une source.

1. La réverbération :
    + Permet de simuler un effet de salle
    + Se décompose en deux parties : premières réflexions et champs diffus
    + S'utilise en insert sur les sources

1. La saturation
    + Est un traitement simple à réaliser en numérique
    + Introduit des problèmes de repliement spectral
    + Peut consommer beaucoup de ressources

1. Le mastering
    + Permet de rattraper un mixage approximatif
    + Est une étape vitale dans la production d'un morceau
    + Consiste à traiter un ensemble de morceaux plutôt qu'un ensemble de piste

1. Cochez les réponses justes :
    + Un bus permet de sommer et véhiculer des signaux
    + Une piste auxiliaire permet de traiter une source en série
    + Une piste auxiliaire peut être utilisée pour des retours casque