# Introduction

## Quelques petites idées

+ La technique n'a de sens que mis au service de l'esthétiques.
+ Tant que l'on est pas satisfait, tout est permis.
+ On a l'écoute de ses compétence

Pour commencer ce guide, je vous propose quelques points de reflexions. Le premier consiste à se rappeler que nos métiers de techniciens du sons ne sont pas des métiers de créateurs. Nous sommes **assistants de créations**. En d'autre mot, nous mettons notre compétence au service de personne en ayant besoin : les artistes. Cela a beaucoup d'implication. Premièrement notre technique, notre équipement, nos méthodes de travail n'intéresse personnes, à part nos paires, et encore moins le public ! Deuxièmement, les artistes, les musiciens ont toujours raison. Même quand ils ont tord, même quand ils se trompent, et même quand nous pouvons le leur prouver. Preneur de son, mixeur et autre, ne sont pas des métiers ou l'égo est grand alié.

Le deuxième point de réflexions résumera assez bien la philosophie de ce livre: en production sonore, tous les coups sont permis. Nous allons, dans les pages qui suivent, voir quantités de techniques, stratégies, savoir qui vous donnerons, je l'espère, une base solide pour la prise de son. Et pourtant, on rencontrera toujours des cas où il faudra faire tout l'opposé de ce que recommande la technique.

Enfin, Gaël Martinet, patron de FLUX:: immersif et créateur des rares plug-ins qui valent la peine d'être utilisés, m'a un jour dit : "on a les oreilles de ses compétence." Je crois qu'il y a beaucoup de vérité dans cette phrase mais je lui préfère la suivante : "on a l'écoute de ses compétences". A mon sens, l'importante conclusion de cette phrase est de toujours faire du mieux que l'on peut le jour d'un enregistrement et de faire mieux la prochaine fois. Il n'y a que deux prises de sons ratés : une prise de son où l'on a rien appris et une prise de son où l'on a rien essayé.

## Quelques mythes du monde de l'audio

+ Le matériel ne fait pas de son, le technicien oui.
+ Nous entendons tous la même chose, seul l'écoute diffère

Le monde de l'audio est un monde fascinant, remplis de domaines et de sujets techniques dont leur seul maitrise justifie l'existance de mêtiers ! Ces vingts dernières années est apparut à grande échalle l'audio numérique, l'audio sur IP, l'audio immersif et bien d'autre.

Cependant, malgré une progression technique réel dans nos métiers, nous continuons à nourrir des mythes tenaces et certain fetichisme envers notre équipement. Je trouve ce grand écart assez curieux et est souvent bien représenté par nos techniciens du monde du live et les techniciens du monde du studio.

Malgré la pandémie mondiale de COVID 19, le monde du live est un monde vivant, en constante évolution. C'est aussi un secteur correctement irrigué, financièrement parlant.

Les studios d'enregistrement, quant à eux, ferment leurs portes. Les grosses structures sont trop chères à maintenir et la plus part des techniciens de ce domaine n'ont pas suivi les évolutions technologiques. Il reste donc un vague souvenir nostalgique, emprunt de "c'était mieux avant". Sans doute, l'économie du disque se portait mieux à la fin du siècle derniers, mais je crois que cela vient nourrir cet absurde nostalgie des machines "vintages", du besoin patologique d'avoir un vrai U47, trois 1176 et des préamplis Neve, sinon, jamais nous ne pourrons faire de beau disque.

Si cette dernière phrase vous parait être du chinois, réjouissez-vous, vous aurez moins d'appréiori à déconstruire. Si ce gentil sarcasme vous a trop aggacé, je crains que le reste de ce livre de soit pas pour vous.

Je ne cherche pas à défendre un vision relativiste des choses. Non, tous les équipements audio ne se valent pas. Oui, il y a des choses de qualité, oui il y a des équipements douteux (et sans doute de plus en plus rarement). Je crois qu'il y a surtout des mauvais usages, et, surtout, le prix d'un équipement n'est pas proportionnel à sa qualité.

Si vous lisez ce livre dans l'espoir de devenir un preneur de son, j'ai donc une bonne nouvelle pour vous. Ce qui fera la différence entre vous et vos concurrent ne sera **jamais** votre équipement, mais votre expérience et votre compétence.

L'autre sujet dont je voudrais discuter est l'idée que certains aurait un oreille unique, par opposition à ceux qui n'aurait pas cette chance. Nous mettons beaucoup trop de pression sur notre faculté à entendre des choses alors qu'il s'agit bien plus d'écouter.

Entendre est par définition une action passive. A peu de chose près, et hors accident de la vie, nous entendons grosso-modo tous la même chose. L'enjeu n'est donc pas d'entendre mais d'écouter. De porter son attention sur des détails, d'être capable de les caractériser et de les corriger si besoin.

J'ai encore une bonne nouvelle pour vous : cette capacité de travail s'acquiert, se travail, s'exerce et s'affine. La moins bonne nouvelle, c'est que ce travail est long et il n'y a pas de raccourcis. Il est courant d'entendre dire que pour acquérir une compétence, cela prend soit dix-milles heures, soit dix ans. Vous savez donc dans quoi vous vous lancez !

## Qu'est ce que le son ?

+ Vibration mécanique d'un fluide
+ Célérité : $340$ $m.s^{-1}$
+ Phénomène oscillatoire
+ Caractérisé par une variation de pression

Commençons par quelques généralités.

En **physique**, le son est une **vibration qui se propage sous forme d'une onde acoustique**, à travers un milieu de transmission tel qu`un gaz, un liquide ou un solide. Il s'agit donc d'un stimulus.

En **physiologie** et psychologie humaines, le son est **la réception de telles ondes et la façon dont le cerveau les perçois**. Il est classiquement admit que seules les sons ayant une fréquences comprise entre **20 Hz et 20 000 Hz** (20 kHz) peuvent être entendu. Nous expliciterons la notion de fréquence plus tard. Les ondes sonores supérieures à 20 kHz sont appelées ultrasons et ne sont pas audibles par l'homme. Les ondes sonores inférieures à 20 Hz sont appelées infrasons. La portée auditive varie selon les espèces animales. Dans ce cas, le son est une sensation.

En résumé, on peut définir le son comme :
+ une **oscillation de pression**, de contrainte, de déplacement de particules, de vitesse de particules, etc., propagée dans un milieu avec des forces internes (par exemple, élastiques ou visqueuses), ou la superposition d'une telle oscillation propagée.
+ une **sensation auditive** évoquée par l'oscillation décrite au point précédent

Le son peut se propager sous forme d'ondes longitudinales et également d'ondes transversales dans les solides et est produit par une source sonore. La source sonore créer des vibrations dans le milieu environnant. Lorsque la source continue à faire vibrer le milieu, les vibrations se propagent à partir de la source à la vitesse du son, formant ainsi l'onde sonore.

+ À une distance fixe de la source, la pression, la vitesse et le déplacement du milieu varient dans le temps.
+ À un instant donné, la pression, la vitesse et le déplacement varient dans l'espace.

> Notez que **les particules** du milieu **ne se déplacent pas** avec l'onde sonore. Cela est intuitif pour un solide, et il en va de même pour les liquides et les gaz. Pendant la propagation, les ondes peuvent être réfléchies, réfractées ou atténuées par le milieu.

Les ondes sonores sont souvent simplifiées en une description en termes d'ondes planes sinusoïdales, qui sont caractérisées par ces propriétés génériques :

+ la **fréquence**, ou son inverse, la **longueur d'onde**
+ l'amplitude, pression acoustique ou **intensité**
+ la **vitesse du son**
+ la direction

La **longueur d'onde** correspond à une distance réalisée par une onde au cours d 'une certaine période et se note $\lambda$. En d'autres termes, il s'agit d 'une grandeur physique qui permet d'étudier les phénomènes périodiques. La **fréquence** (Hz), l'inverse de la longueur d'onde, décrit le nombre d'oscillation d'une onde par seconde.

Un **son** est dit "**pur**" si il n'est composé que d'une seule fréquence. De tels sons n'existent pas naturellement et correspondent bien souvent à des signaux de test (recherche en laboratoire où outil de calibration d'équipement électronique). La plupart des sons rencontrés sont composés de plusieurs fréquences. La fréquence constituante d'un son la plus grave (ou la plus basse) est appelée **fréquence fondamentale**. Si les autres fréquences constituantes sont des multiples de la fréquence fondamentale alors celle-ci sont qualifié d'**harmoniques**. Sinon elles sont appelées partielles. L'ensemble de ces fréquences est appelé le **spectre sonore**.

La **vitesse du son** dépend du milieu traversé et de sa température. Dans un air à 20 °C au niveau de la mer, la vitesse du son est d'environ **343 m/s**, soit 1230 km/h. Il est important de connaitre la vitesse du son par coeur. On retient généralement la valeur de **340 m/s**. Cela permet de rapidement calculer le retard perçus entre deux sources sonores placés à des endroits différents. De même, connaitre la distance entre deux microphones permet de calculer la différence de temps parcourus par une onde sonore pour atteindre le microphones le plus éloigné. On utilisera pour cela la formule suivante : $v = d / t$.

La **pression acoustique** est la différence, dans un milieu donné, entre la pression locale moyenne et la pression de l'onde sonore. Le carré de cette différence (c'est-à-dire le carré de l'écart par rapport à la pression d'équilibre) est généralement moyenné dans le temps et/ou l'espace, et la racine carrée de cette moyenne donne une **valeur quadratique moyenne (RMS)**.

## Comment décrire un son ?

<!-- Il est important pour un technicien d'avoir une représentation clair de la physique d'une onde sonore. Cependant les descriptions physique et mathématique de tels ondes ne -->

+ Hauteur
+ Timbre
+ Enveloppe

La **hauteur d'un son** est définie par la **hauteur de sa fréquence fondamentale**. Plus celle-ci est aigüe, plus le son sera qualifié de "haut". A l'inverse, plus celle-ci est grave, plus le son sera qualifié de "bas".

Le **timbre** est une qualification du **spectre sonore** d'un son. Il n'y a rien d'absolu dans la façon dont nous qualifions un timbre (même un son en général). On parlera donc de son "chaud", "brillant", "rond", "ouvert", "criard", "aggressif", "boueux", "épais", "gras", etc. Tout ces termes étant tous plus inefficace les uns que les autres pour décrire le spectre d'un son. Et pourtant, nous les utilisons tous. La manque de vocabulaire précis pour qualifié le son n'est pas un problème nouveau. Nous sommes toujours obligé de retrouver le lien entre le qualificatif employé et la sensation perçue par notre interlocuteur. Une fois la sensation définie, il convient de l'associer à une donnée physique et donc à une bande fréquentielle précise. Etre capable de traduire un qualificatif parfois hazardeux en un geste technique fait parti intégrante des compétences nécéssaires à un ingénieur du son.

L'enveloppe d'un son est une description de l'évolution de son intensité dans le temps. On la décompose classiquement en quatre parties :

+ l'attaque (attack)
+ la décroissance (decay)
+ le maintient (sustain)
+ le relâchement (release)

L'**attaque** est le temps mit par le son pour atteindre son intensité maximale.

La **décroissance** est le temps mit pour le son pour atteindre un niveau stationnaire

Le **maintient** est le temps durant lequel l'intensité sonore du son ne varie pas

La **relâchement** est le temps mis par un son pour s'éteindre.

On parle de transitoire (transient en anglais) lorsque que les temps d'attaque et de décroissance d'un son sont très court.

Les instruments percussifs se caractérisent pas des enveloppes courtes, là ou les instruments harmoniques et mélodiques tendant à avoir des enveloppes plus longues.