# Historique de la spatialisation {#sec-hist-spat}

De nos jours, (2023 à l'écriture de ce chapitre), le "son immersif" semble être faire partie des nouvelles technologies et la plupart des fabricants se lancent sur ce marché. Il est d'ailleurs très fréquent de voir ce "son immersif" vendu comme quelque chose de nouveau et d'inédit. Pourtant, la question de l'espace sonore, de sa capture et de sa restitution est presque aussi vieille que celle de l'enregistrement.

Nous tâcherons dans ce chapitre de retracer une histoire du son spatialisé, en abordant l'apparition des différentes techniques, mais aussi leurs concepteurs, et les ingénieurs qui y ont participés. Nous traverserons donc près de cent-cinquante années d'histoire, en commençant par les premiers essaies de son "stéréophonique" jusqu'au mixage orienté objet et des opportunités de spatialisation qu'il offre. D'autres part, nous tâcherons également de parler des compositeurs et des artistes qui se sont accaparés la question de l'espace et sa réstitution dans leur oeuvre.

Ce chapitre ne peut évidement pas être exhaustif, mais essaye tout de même de donner une image d'ensemble assez juste.

<!-- 

[Histoire de l'enregistrement sonore](https://www.aes.org/e-lib/browse.cfm?elib=16983)

[History of Spatial Coding](https://www.aes.org/e-lib/browse.cfm?elib=12218)

[Son Stéréophonique](https://fr.wikipedia.org/wiki/Son_stéréophonique)

[Binaural history Pt.1](https://www.linkedin.com/pulse/history-binaural-audio-part-1-anthony-mattana)

[Binaural history Pt.2](https://www.linkedin.com/pulse/history-binaural-audio-part-ii-resurgence-1940-2000-anthony-mattana)

 -->

## De la monophonie à la stéréophonie : un besoin d'espace

Pendant près de quatre-vingt ans, la majorité des systèmes de diffusion sonores sont monophoniques. Il faut en effet attendre la fin des années soixantes pour que l'écrasante majoritée de la musique enregistrée soit produite en stéréophonie. Avant cela, le norme est donc à une écoute ne se constituant que d'un seul haut-parleur.

Pourtant, le besoin d'espace dans la restitution sonore se fait sentir très tôt, car plusieurs ingénieurs se penchent sur cette question dès le début du XXème siècle. Il semble que le premier à proposer un système de diffusion sur deux canaux soit **[Clément Ader](https://fr.wikipedia.org/wiki/Clément_Ader)** (1841-1925). Cet ingénieur français est avant tout connu pour être le premier à avoir fait décoller un engin motorisé plus lourd que l'air en 1890. Il a également participé au déploiment du réseau téléphonique, à Paris, en 1879. C'est à ce moment qu'il a l'idée d'utiliser le réseau de télécommunication pour diffuser l'opéra dans les foyers. Ce dispositif, nommé **[Théâtrophone](https://fr.wikipedia.org/wiki/Théâtrophone)**, est pour la première fois utilisé en 1881. Les auditeurs peuvent alors écouter la pièce retransmise en direct en plaçant un "écouteurs" sur chacune de leurs oreilles. La diffusion se fait donc sur deux canaux.

A cette époque, les seuls microphones disponibles sont des microphones à charbons, dont on connait la faible bande passante. La qualité sonore du dispositif est donc médiocre, mais l'angouement du public est réel, et perdurera jusque dans les années 1930.

La stéréophonie va être pensée, quasiment simultanément par deux ingénieurs, **[Arthur C. Keller](https://en.wikipedia.org/wiki/Arthur_C._Keller)** (1901-1983) et **[Alan D. Blumlein](https://en.wikipedia.org/wiki/Alan_Blumlein)** (1903-1942). Le premier travail aux laboratoires Bells, sous la direction d'**[Harvey Fletcher](http://www.byhigh.org/History/Fletcher/DrHarvey.html)** (le même Fletcher que les courbes [Flecther-Munson -@fig-isosonie]). Keller se retrouve à travailler sur la diffusion stéréophonique car on demande au chef d'orchestre **[Leopold Stokowski](https://en.wikipedia.org/wiki/Leopold_Stokowski)** de produire des concerts sur les ondes de la NBC avec l'orchestre de Philadelphia. Stokowski est, à l'époque, très insatisfait de rendu sonore de ce type de dispositif et contact alors les laboratoires Bells pour y apporter une solution. De cette collaboration naît une collection d'enregistrements dont le plus vieux semble être cette interprétation du [Le Carnaval romain (Ouverture)](https://www.stokowski.org/sitebuilderfiles/311201_Roman_Carnival_MA.mp3) de Berlioz, interprété le cinq décembre 1931.

De l'autre côté de l'océan, Alan Blumlein travail pour la **[Colombia Graphophone Company](https://en.wikipedia.org/wiki/Columbia_Graphophone_Company)**. L'histoire veut qu'il soit frustré de son expérience du son au cinéma, ne comprenant pas pourquoi les voix sont toutes au centre alors que les acteurs se déplacent de part et d'autre de l'écran. Blumlein va donc proposer, pêle-mêle, les techniques de prises de son coincidente XY/Blumlein et MS (pour garantir la rétro-compatibilité sur les système mono), un système de gravure à deux canaux sur disques microsillons et la discription du système d'enceinte que l'on utilise encore aujourd'hui sous le nom stéréphonie. Il est amusant de constater que dans ses écris, Blumlein ne parle pas de son stéréophonique mais de son binaural. Ceci est d'autant plus surprenant qu'il est le premier à revendiquer l'idée que les haut-parleurs, dans un système stéréophonique, ne correspondent pas aux oreilles, et qu'il convient donc d'étudier ce système avec une approche psycho-acoustique. Blumlein invente également un système, qu'il appelle "shuffling", permettant de convertir une différence de phase en différence d'intensité. Pour lui, ce dispositif fait parti intégrante d'un système de prise de son stéréophonique. Cependant, ce "shuffler" ne sera pas du tout employé dans le reste de l'industrie.

:::{.callout-note}

En 1931, La Colombia Graphophone Company et la [Gramophone Company](https://en.wikipedia.org/wiki/Gramophone_Company) fusionnent pour devenir [EMI](https://en.wikipedia.org/wiki/EMI).

:::

Il existe encore quelques enregistrements du travail d'Alan Blumlein, par exemple, cette démonstration du [mouvement en stéréophonie](https://www.youtube.com/watch?v=rqaMiDqE6QQ) (dans un style tout à fait anglais), ou encore cette interprétation de la [Chevauchée des Valkyries pour trois pianos](https://www.youtube.com/watch?v=gfWuIEgGUJk) enregistrée à Abbey Road. Ces deux enregistrements dates de 1931.

:::{.callout-note}

Le procédé de gravure stéréophonique sur microsillon de Keller et Blumlein est très proche, cependant, il ne semble qu'aucun des deux n'ai eu connaissance des travaux de l'autre. Keller aurait développé sont système avant Blumlein, mais ce dernier a publié son brevet en premier. Les deux approches reposent sur l'idée de gravé les deux canaux à 45° de la verticale. Ce procédé semble être tombé dans l'oublie jusqu'à sa "[réinvention](https://ieeexplore.ieee.org/document/4065276)" dans les années cinquantes par la société Westrex.

:::

Blumlein décède en plein milieu de la seconde guerre mondiale suite au crash du bombardier Helifax, dans lequel il effectuait des tests sur le système de [radar H2S](https://en.wikipedia.org/wiki/H2S_radar).

<!-- [Archives EMI Blumlein](https://www.emiarchivetrust.org/alan-blumlein-and-the-invention-of-stereo/) -->

<!-- [Stereophonie 1931-1932](https://www.stokowski.org/Harvey_Fletcher_and_Bell_Labs_Stereo.htm) -->

## Alan Blumlein (1903-1942)

[Biographie](https://en.wikipedia.org/wiki/Alan_Blumlein)

[United Kingdom patent 394325 'Improvements in and relating to Sound-transmission, Sound-recording and Sound-reproducing Systems'](https://en.wikipedia.org/wiki/United_Kingdom_patent_394325)

[The Inventor of Stereo: The life and works of Alan Dower Blumlein](https://books.google.fr/books?id=bkl5AgAAQBAJ&printsec=frontcover&hl=fr&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false)

[Gerzon, Michael (1994). "Application of Blumlein Shuffling to Stereo Microphone Techniques"](http://decoy.iki.fi/dsound/ambisonic/motherlode/data/6939.pdf)

[Couple de prise de son Blumlein](https://en.wikipedia.org/wiki/Blumlein_pair)

## Pierre Schaeffer (1910-1995)

[Biographie](https://fr.wikipedia.org/wiki/Pierre_Schaeffer)

## Iannis Xenakis (1922-2001)

[Biographie](https://fr.wikipedia.org/wiki/Iannis_Xenakis)

## Pierre Henry (1927-2017)

[Biographie](https://fr.wikipedia.org/wiki/Pierre_Henry)

## Michael Gerzon (1945-1996)

[Biographie](https://en.wikipedia.org/wiki/Michael_Gerzon)

[Site homage](https://www.michaelgerzonphotos.org.uk)

[Archives d'articles Hi-Fi news](http://www.audiosignal.co.uk/Gerzon%20archive.html)

[Ambisonique du 1e ordre](https://en.wikipedia.org/wiki/Ambisonics)

[Archives sonores des enregistrements de Michael Gerzon](https://econtact.ca/10_x/archive_britishlibrary.html#gerzon)

[Into The Soundfield](https://intothesoundfield.music.ox.ac.uk/michael-gerzon-story)

[Practical periphony: the reproduction of full-sphere sound](https://intothesoundfield.music.ox.ac.uk/sites/default/files/intothesoundfield/documents/media/practical_periphony_the_reproduction_of_full_sphere_sound_michael_gerzon_draft_for_aes_london_feb_1980.pdf)

## L'IRCAM : Institut de recherche et coordination acoustique/musique (1970)


## Dolby


## DTS


## Sony

<!-- 

http://www.widescreenmuseum.com/sound/fantasound1.htm

 -->

<!-- 

Source : https://www.informit.com/articles/article.aspx?p=337317

You might think that surround sound is a relatively new development. But the concept of having a soundtrack surrounding the listener starts well before today's home theater era—in fact, it dates all the way back to the 1940s!

Surround Sound in the Movies
Surround sound started as a way to immerse movie-going audiences in the film they were watching. From the very beginning, the movies have driven the development of surround sound technology.

The 1940s: Fantasia
In many ways, Walt Disney can be considered the inventor of surround sound. When the groundbreaking movie Fantasia was still in development, Disney met with conductor Leopold Stokowski to discuss the film's classical music score. Stokowski suggested that Disney contact the engineers at Bell Labs, who were working on a nascent multiple-microphone stereo recording technology. Intrigued by the technology, Disney thought it would be wonderful if, during the movie's "Flight of the Bumblebee" segment, the musical sound of the bumblebee could be heard flying all around the audience, not just in front of them.

Disney put his engineers to work on the challenge, with the result that Fantasia, released in 1941, became the very first film to incorporate surround sound. Disney employed the proprietary Fantasound technology to create a surround sound field with left front, center front, right front, left rear, and right rear channels. The main soundtrack incorporated only the front three channels; the two rear channels were recorded on a separate reel of film, and "steered in" separately when needed.

Unfortunately, the additional equipment necessary to reproduce Fantasound was too costly to roll out on a widespread basis. Only two Fantasound systems were sold to theaters: New York's Broadway Theater and the Carthay Circle Theater in Los Angeles. These installations cost $85,000 apiece and included 54 speakers placed throughout the auditorium. Disney also produced two scaled-back road show versions of the Fantasound system, at $45,000 each, although these traveling versions didn't include the surround speakers.

The 1950s: Multiple-Channel Stereo
The Fantasound system proved too complex and too costly for other studios to adopt. It took another decade for Hollywood to embrace a more affordable multiple-channel sound technology—which it did in conjunction with the birth of the new widescreen film formats, in particular Cinerama and CinemaScope.

The new wider-screen formats needed multiple channels to fill the entire front field of the movie screen. The solution was a wall of sound, employing four to six audio channels for a widescreen stereo effect. Among the earliest multiple-channel movies were 1952's This is Cinerama (with seven-channel surround sound) and 1953's The Robe (in Cinemascope, with four-channel sound).

Prior to this point, one sound channel was optically encoded onto a strip of film, the same way the picture itself was recorded. To fit more sound tracks onto a strip of film, multiple tracks were encoded magnetically. A film frame has room for up to six of these magnetic audio tracks. Several of the early widescreen formats added a surround sound channel to this standard stereo setup. In a standard four-channel setup, the tracks are assigned to left, center, right, and surround. The mono surround channel was fed to multiple speakers along the sides and rear of the theater. The surround channel was typically used for ambient background noise or other sound effects, thus inspiring the name "effects channel."

Unfortunately, the cost of these technologies proved prohibitive, and theatrical surround sound died out by the end of the 1950s.

The 1970s: Dolby Stereo
True surround sound made a comeback in the 1970s with the introduction of Dolby Stereo. In spite of its name, this was an optical four-channel technology, introduced in 1976 by Dolby Laboratories.

Instead of using magnetic audio tracks, which tended to be of lower fidelity, Dolby reverted back to the earlier—and superior—optical recording technology. It also added noise-reduction technology for clearer playback.

The big boost for surround sound was the release of a single movie—1977's Star Wars, with its swooping rear-channel effects. The success of Star Wars inspired theater owners to upgrade their sound equipment to the Dolby Stereo standard, and led to other producers and studios embracing the surround sound format.

The 1980s: Dolby SR and THX
Throughout the 1980s, more and more movies employed the Dolby Stereo surround sound system. In 1983, Lucasfilm introduced THX certification (named after George Lucas' first film, THX 1138), a set of technical standards designed to ensure a high-quality playback of film soundtracks in specially equipped movie theaters. In 1987, Dolby introduced Dolby SR, an optical four-channel system that offered wider dynamic range and a broader frequency response than the previous Dolby Stereo system.

The 1990s: Dolby Digital Surround, DTS, SDDS, and EX
Cinema surround sound became digital in 1992 with the introduction of Dolby Digital Surround (originally known as Dolby AC-3, short for audio coding 3). This system still encodes the audio information on a film's optical tracks, but in digital format instead of in analog fashion. Dolby Digital also introduced more channels—a 5.1 configuration with left front, center front, right front, left surround, right surround, and a separate low frequency effects (LFE) channel for deep bass.

In 1993, the Digital Theater Systems company introduced the competing DTS surround sound technology. Like Dolby Digital, DTS is a digital 5.1-channel system. Unlike Dolby Digital, however, DTS records the audio channels on CD, which on playback is synchronized to the film's time code. The first DTS movie was 1993's Jurassic Park.

A third company entered the surround-sound fray in 1993. Developed by Sony, the Sony Dynamic Digital Sound (SDDS) technology is an optical system like Dolby Digital, but with 7.1 channels arranged in a unique pattern—five front channels (left, left center, center, right center, right), left and right surrounds, and the low frequency effects (subwoofer) channel. This multiple-front speaker system purportedly produces better dialogue imaging; the first SDDS film was 1993's The Last Action Hero.

In 1999, Dolby introduced yet another new surround sound technology, Dolby Digital Surround EX. This 6.1-channel optical system adds a rear surround channel to the previous left and right surrounds. The first EX movie was Star Wars: Episode One—The Phantom Menace.











Surround Sound at Home
In the home, multiple-channel sound had its origins with the reproduction of music in stereo. Multiple-channel technology only recently expanded to accommodate surround sound movie soundtracks.

Early Multiple-Channel Experiments
For decades, music recording and reproduction was monophonic. However, there was a real desire for a multiple-channel system to more accurately represent the live musical experience. Initial industry experiments with stereo recording took place in the early 1930s. These early experiments employed an "infinite" number of microphones deployed in a type of curtain in front of the recording musicians, and an equal number of speakers used to reproduce the sound. Later, engineers discovered that they could use phantom imaging to reproduce the stereo soundstage with just two speakers.

The 1950s and 1960s: Stereophonic Sound
Practical multiple-channel recording came into being in the 1950s with the introduction of the two-channel stereophonic system. The first commercial two-channel stereo LP was released in 1958, and by the early 1960s stereo recordings became the norm. Stereo reproduction over the airwaves began in 1961, when the first stereo FM radio broadcast took place.

Early 1970s: Quadraphonic Sound
The desire to reproduce a 360-degree sound field led to the development of four-channel, or quadraphonic, recording. Quadraphonic sound officially debuted in 1969 with the release of the first consumer-level four-channel reel-to-reel tape deck. Soon the quadraphonic process was being applied to both eight-track tapes and vinyl records.

By the early 1970s multiple quadraphonic technologies were competing in the marketplace. JVC's CD-4 system, introduced in 1971 for vinyl records, employed four discrete channels of audio information—front left, front right, rear left, and rear right. The SQ and QS systems, introduced in 1972 by CBS and Sansui, respectively, were both matrix technologies for vinyl records, in which the rear channel information was matrixed into the two front channels and then separated out by a surround decoder. And RCA's Quad-8 format, introduced in 1970, was a discrete format designed specifically for eight-track tape players.

Unfortunately, the confusion generated by these competing technologies, along with the high cost of four-channel amplifiers and additional rear speakers, led to the abandonment of quadraphonic sound by the end of the decade.

Late 1970s: Stereo Video
Even though stereo audio recordings and broadcasts had been around since the late 1950s, it took until the late 1970s for stereo sound to be applied to video recordings and broadcasts. The first two-channel stereo videocassette was released in 1978, and the first stereo television broadcasts occurred in 1986.

The 1980s: Dolby Surround and Dolby Pro Logic
True surround sound came to the home in 1982, with the introduction of Dolby Surround technology. Dolby Surround was designed to reproduce the cinema's Dolby Stereo surround soundtracks in a home environment. The Dolby Surround technology consisted of three channels—left, right, and a single surround channel, which was matrixed in with the front two channels. (This single surround channel was frequently sent to two rear speakers, resulting in a four-speaker system.)

Dolby Surround got an upgrade in 1987, when the Dolby Pro Logic system was introduced. Dolby Pro Logic is a four-channel version of the early three-channel Dolby Surround technology, with a separate center channel, primarily used for dialogue. To this day, Dolby Pro Logic is the surround sound standard for prerecorded VHS videotapes.

The 1990s: Dolby Digital and DTS
Home surround sound went digital in 1995 with the introduction of the first Dolby Digital laserdisc. Like the cinema version, home Dolby Digital is a 5.1-channel system, with left front, center front, right front, left surround, and right surround, along with a separate LFE or subwoofer channel. The first Dolby Digital DVD was released in 1997; Dolby Digital is also the official sound format for high-definition television broadcasts.

The competing DTS system was released in a home version in 1996. DTS works similarly to Dolby Digital, but with higher data rates, which often results in slightly better sound quality. However, DTS is an optional format for the home theater environment, and is not included on many DVDs; there are many more DVDs with Dolby Digital soundtracks than with DTS soundtracks.

2000 and Beyond: More Channels, More Options
The new millennium brought significant enhancements to all the major home surround-sound technologies. Dolby Laboratories introduced the concept of rear channels to the mix, placed behind the listener to supplement the normal side-firing surround speakers. The new system, Dolby Digital EX, is available with either single (6.1) or right and left (7.1) rear channels. The new rear channels are matrixed into the original channels, and then subtracted out via a surround decoder.

DTS also embraced the separate surround and rear channel concept with DTS-ES. This is a 6.1/7.1-channel system with matrixed rear channels. However, DTS upped the ante with DTS-ES Discrete, which uses a discrete rear surround channel for better channel separation.

Finally, the aging matrix-surround approach got a boost with Dolby Pro Logic II. This new technology is designed to simulate a surround sound field from two-channel sources; you use it to listen to stereo soundtracks in a surround sound system. (Dolby Pro Logic IIx is an enhanced version designed for 7.1-channel systems.)

Going forward, it's likely that new developments will focus on adding even more channels to the surround mix (possibly wide left and wide right front channels, as well as additional side channels) to more accurately reproduce a true 360-degree sound field.


 -->